# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175eaed13e29d93059cd1dd2c09d96e5ed374f02e6330d477d13b384e9286416aa04c07c138f494ea0563236bfac732c37e0600ccff8e749842f9e906e21c5de

test:
  secret_key_base: a85b42851eb17580e586836de4379e42d2f5a2b14a03d42e05c38e9bab56a10b27e12709bec1815874c01209c3eb3e3f1d53262c6349f7fc335556778e943c08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
